name: Build Backend CI

on:
  workflow_dispatch:
    inputs:
      refToBuild:
        description: 'Branch, tag or commit SHA1 to build'
        required: true
        type: string
  push:
    branches:
      - main
    paths:
      - '../DashboardAPI'
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.2
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3.1.0
        with:
          username: ${{secrets.DOCKERHUB_USER}}
          password: ${{secrets.DOCKERHUB_PWD}}
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v5.3.0
        with:
          context: DashboardAPI/
          file: DashboardAPI/Dockerfile
          push: true
          tags: bruno0m/dashboard-api:latest
