name: Build Backend CI

on:
  push:
    branches:
      - main
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.2

      - name: Lowercase GITHUB_REPOSITORY
        id: lowercase
        run: |
            echo "repository=${GITHUB_REPOSITORY,,}" >> "$GITHUB_OUTPUT"

      - name: Docker image metadata
        id: meta
        uses: docker/metadata-action@v5.5.1
        with:
          images: ghcr.io/${{ steps.lowercase.outputs.repository }}/dashboard-api
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3.1.0
        with:
          username: ${{secrets.DOCKERHUB_USER}}
          password: ${{secrets.DOCKERHUB_PWD}}
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v5.3.0
        with:
          context: DashboardAPI/DashboardAPI/DashboardAPI
          file: DashboardAPI/DashboardAPI/DashboardAPI/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
